import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styled from 'styled-components'
import { loadData } from '../lib/load-data'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

interface GalleryItemDetails {
  "albumId": number,
  "id": number,
  "title": string,
  "url": string,
  "thumbnailUrl": string
}

interface IGalleryProps {
  data: GalleryItemDetails[]
}

export async function getStaticProps() {
  const data = await loadData()
  return {
    props: {
      data
    }
  }
}

const sizes = {
  tablet: '767px',
  laptop: '1024px',
  laptopL: '1440px',
}

const devices = {
  tablet: `(min-width: ${sizes.tablet})`,
  laptop: `(min-width: ${sizes.laptop})`,
  laptopL: `(min-width: ${sizes.laptopL})`,
}

const Gallery = styled.div`
padding: 5rem 2rem;
text-align: center;
display: grid;
grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
gap: 1rem;
`
const GalleryItem = styled.div`
& > img {
    height: 100%;
    width:100%;
    object-fit:cover;
} 
`
const Button = styled.button`
border: none;
background-color: grey;
color: white;
padding: 1rem 2rem;
border-radius: 3px;
margin-bottom: 3rem;
cursor: pointer;
`

export default function Home({ data }: IGalleryProps) {
  const [postNo, setPostNo] = useState<number>(10)
  const dataLength = data.length
  console.log(dataLength)
  console.log(postNo)
  const post = data.slice(0, postNo)
  function loadMore() {
    setPostNo(prevNo => prevNo + 10)
  }
  function showLess() {
    setPostNo(10)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>
          Image Gallery
        </h1>
      </header>
      <main>
        <Gallery>
          {post.map(item => {
            return (
              <GalleryItem key={item.id}>
                <Image
                  src={item.thumbnailUrl}
                  alt=""
                  width={100}
                  height={100}
                />
              </GalleryItem>
            )
          })}
        </Gallery>
        {
          postNo !== dataLength ?
            <Button onClick={loadMore}>Load more</Button>
            :
            <Button onClick={showLess}>Show Less</Button>
        }
      </main>
    </>
  )
}
